export const countries = [
  { code: "ZAF", name: "Afrique du Sud" },
  { code: "DZA", name: "Algérie" },
  { code: "AGO", name: "Angola" },
  { code: "BEN", name: "Bénin" },
  { code: "BWA", name: "Botswana" },
  { code: "BFA", name: "Burkina Faso" },
  { code: "BDI", name: "Burundi" },
  { code: "CMR", name: "Cameroun" },
  { code: "CPV", name: "Cap-Vert" },
  { code: "CAF", name: "République centrafricaine" },
  { code: "TCD", name: "Tchad" },
  { code: "COM", name: "Comores" },
  { code: "COG", name: "Congo-Brazzaville" },
  { code: "COD", name: "Congo-Kinshasa" },
  { code: "CIV", name: "Côte d'Ivoire" },
  { code: "DJI", name: "Djibouti" },
  { code: "EGY", name: "Égypte" },
  { code: "GNQ", name: "Guinée équatoriale" },
  { code: "ERI", name: "Érythrée" },
  { code: "SWZ", name: "Eswatini" },
  { code: "ETH", name: "Éthiopie" },
  { code: "GAB", name: "Gabon" },
  { code: "GMB", name: "Gambie" },
  { code: "GHA", name: "Ghana" },
  { code: "GIN", name: "Guinée" },
  { code: "GNB", name: "Guinée-Bissau" },
  { code: "KEN", name: "Kenya" },
  { code: "LSO", name: "Lesotho" },
  { code: "LBR", name: "Libéria" },
  { code: "LBY", name: "Libye" },
  { code: "MDG", name: "Madagascar" },
  { code: "MWI", name: "Malawi" },
  { code: "MLI", name: "Mali" },
  { code: "MRT", name: "Mauritanie" },
  { code: "MUS", name: "Maurice" },
  { code: "MAR", name: "Maroc" },
  { code: "MOZ", name: "Mozambique" },
  { code: "NAM", name: "Namibie" },
  { code: "NER", name: "Niger" },
  { code: "NGA", name: "Nigeria" },
  { code: "RWA", name: "Rwanda" },
  { code: "STP", name: "Sao Tomé-et-Principe" },
  { code: "SEN", name: "Sénégal" },
  { code: "SYC", name: "Seychelles" },
  { code: "SLE", name: "Sierra Leone" },
  { code: "SOM", name: "Somalie" },
  { code: "SDN", name: "Soudan" },
  { code: "SSD", name: "Soudan du Sud" },
  { code: "TZA", name: "Tanzanie" },
  { code: "TGO", name: "Togo" },
  { code: "TUN", name: "Tunisie" },
  { code: "UGA", name: "Ouganda" },
  { code: "ZMB", name: "Zambie" },
  { code: "ZWE", name: "Zimbabwe" },
];
